name: flutter_jl_ota
description: "A Flutter plugin for Over-The-Air (OTA) firmware updates targeting JL (JieLi) chipsets. Supports Android and iOS platforms with progress callbacks and error handling."
version: 1.0.4
homepage: "https://github.com/futurpals/flutter_jl_ota"
repository: "https://github.com/futurpals/flutter_jl_ota"
issue_tracker: "https://github.com/futurpals/flutter_jl_ota/issues"

environment:
  sdk: ^3.7.2
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.futurpals.flutter_jl_ota
        pluginClass: FlutterJlOtaPlugin
      ios:
        pluginClass: FlutterJlOtaPlugin
